[tool.ruff]
line-length = 88

# Ignore line length errors in specific directories with many issues
[tool.ruff.per-file-ignores]
"templates/prompts/*.py" = ["E501"]
"backup/*.py" = ["E501"]
"tests/*.py" = ["E501", "E402"]
"test/*.py" = ["E501", "E402"]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disable_error_code = ["attr-defined", "no-any-return", "var-annotated", "union-attr", "return-value", "assignment", "index"] 